import { Pic } from './pic.model';

export const picsData: Pic[] = [
  {
    id: 1,
    title: 'First Strawberries',
    url: 'https://i.postimg.cc/Gprypgr4/1719220459506.jpgs',
    text: "Ah, the first wild strawberries of summer, A burst of sweetness, a vibrant color. Nature's gift, a taste of pure delight, Juicy and ripe, a true seasonal delight.",
    date: '23-06-2024',
  },
  {
    id: 2,
    title: 'Good Morning Forest',
    url: 'https://i.postimg.cc/d1VZ27hv/1719133713383.jpg',
    text: "'Every morning we are born again. What we do today is what matters most.'",
    signature: 'by Buddha',
    date: '23-06-2024',
  },
  {
    id: 3,
    title: 'Enjoying the Walk',
    url: 'https://i.postimg.cc/2yPqN228/1719133662313.jpg',
    text: "'Happiness will never come to those who fail to appreciate what they already have.'",
    signature: 'by Buddha',
    date: '23-06-2024',
  },
  {
    id: 4,
    title: 'Daisies',
    url: 'https://i.postimg.cc/MKzstT1D/1718714200420.jpg',
    text: "Amongst the daisies, one finds a lesson in impermanence. Just as the petals bloom and wither, so too do our moments of joy and sorrow pass. The daisies sway in the breeze, a gentle reminder of the ever-changing nature of existence. In their simplicity, daisies teach us to appreciate the beauty in each fleeting moment, to embrace life's transience with grace and acceptance.",
    date: '16-06-2024',
  },
  {
    id: 5,
    title: 'Listening Bells',
    url: 'https://i.postimg.cc/sXSnHGnn/1718714200423.jpg',
    text: '"The most precious gift we can offer anyone is our attention. When mindfulness embraces those we love, they will bloom like flowers."',
    signature: 'by Thich Nhat Hanh',
    date: '16-06-2024',
  },
  {
    id: 6,
    title: 'The Moment',
    url: 'https://i.postimg.cc/wTWkVkqq/1718714200426.jpg',
    text: '"One moment can change a day, One day can change a life and One life can change the world"',
    signature: 'by Buddha',
    date: '12-06-2024',
  },
  {
    id: 7,
    title: 'Going inside the Forest',
    url: 'https://i.postimg.cc/Rh7DhJK3/1718714301372.jpg',
    text: '"All you need to know is that the future is wide open and you are about to create it by what you do."',
    signature: 'by Pema Chodron',
    date: '15-06-2024',
  },
  {
    id: 8,
    title: 'Look inside',
    url: 'https://i.postimg.cc/fL0F4rbf/1718714301379.jpg',
    text: '"The answer lies within ourselves. If we cannot find peace and happiness there, it is not going to come from the outside."',
    signature: 'by Tenzin Palmo',
    date: '15-06-2024',
  },
  {
    id: 9,
    title: 'Cat in the Garden',
    url: 'https://i.postimg.cc/bNjXPpkD/storage-emulated-0-Android-data-com-miui-gallery-cache-Security-Share-1718716419734.jpg',
    text: '"Let your curiosity be greater than your fear."',
    signature: 'by Pema Chodron',
    date: '14-06-2024',
  },
  {
    id: 10,
    title: 'Intrigued Cat',
    url: 'https://i.postimg.cc/vmmFKh90/1718716419738.jpg',
    text: '"Nothing ever goes away until it has taught us what we need to know."',
    signature: 'by Pema Chodron',
    date: '14-06-2024',
  },

  {
    id: 11,
    title: 'Geranios',
    url: 'https://i.postimg.cc/gkxSWZCh/1718362941135.jpg',
    text: '"Colorful geraniums that can be seen hanging on the walls of balconies are plants that captivate hearts with the tones that their petals preserve. The strong passionate red appears, the immaculate white in the corollas, they are flowers illuminated by streetlights, they reflect the illusion that is greening."',
    signature: 'by Fabio Robles',
    date: '12-06-2024',
  },
  {
    id: 12,
    title: 'Wild Flowers',
    url: 'https://i.postimg.cc/FRhC5nvF/1718362941118.jpg',
    text: 'The Aragon Pyrenees, a mountain range straddling the border between France and Spain, is a haven for wildflower enthusiasts.  From vibrant purple crocuses blanketing the slopes in spring to delicate alpine blooms carpeting the high meadows in summer, the region boasts a diverse and colorful tapestry of wildflowers.',
    date: '12-06-2024',
  },
  {
    id: 13,
    title: 'Piñas',
    url: 'https://i.postimg.cc/brBmnytd/1718362941154.jpg',
    text: 'The Aragon Pyrenees, with their vast stretches of pine forests, are home to several species of pine trees, each producing distinct pine cones.',
    date: '11-06-2024',
  },
  {
    id: 14,
    title: 'White Bells',
    url: 'https://i.postimg.cc/2y6H3b3P/1718362941166.jpg',
    text: '"The little things? The little moments? They are not little."',
    signature: 'by Jon Kabat-Zinn',
    date: '11-06-2024',
  },
  {
    id: 15,
    title: 'Pink Stars',
    url: 'https://i.postimg.cc/CMPPXNQY/1718362941182.jpg',
    text: '"He who has little is not poor, but he who desires much"',
    signature: 'by Seneca',
    date: '11-06-2024',
  },
  {
    id: 16,
    title: 'Purple Sticks',
    url: 'https://i.postimg.cc/KY2JBsR7/1718362941194.jpg',
    text: "The flowers of life's impermanence are not a cause for despair, but a reminder to cherish the present moment. Appreciate the beauty of the bloom in its entirety, from the vibrant hues of its petals to the delicate dewdrops clinging to its leaves.",
    date: '11-06-2024',
  },
  {
    id: 17,
    title: 'Purple Bell',
    url: 'https://i.postimg.cc/VL27LNwV/1718362941205.jpg',
    text: '"The bell of mindfulness is the voice of the Buddha within. Every sound can be a bell, calling us back to the present moment."',
    signature: 'by Thich Nhat Hanh',
    date: '11-06-2024',
  },
  {
    id: 18,
    title: 'Bright Sunset',
    url: 'https://i.postimg.cc/7L3tRrpQ/1718363021815.jpg',
    text: '"If you are attached to this life, you are not a Dharma practitioner. If you are attached to samsara, you have no renunciation. If you are attached to your own personal interest, you have no bodhicitta. If attachment arises, you do not have the vision."',
    signature: 'by Manjushri',
    date: '11-06-2024',
  },

  {
    id: 19,
    title: 'Cloud over the mountains',
    url: 'https://i.postimg.cc/C1KchfW8/1718363748142.jpg',
    text: '"Everything is subject to change. Nothing stays the same for long."',
    signature: 'by Buddha',
    date: '11-06-2024',
  },
  {
    id: 20,
    title: 'Cloudy Morning',
    url: 'https://i.postimg.cc/P5jst2K8/1718363764193.jpg',
    text: '"True peace comes from within you, it is not found anywhere else nor does it come from the hand of any person or thing. Peace is found in you."',
    signature: 'by Buddha',
    date: '11-06-2024',
  },
  {
    id: 21,
    title: 'Wild Meadow',
    url: 'https://i.postimg.cc/G2354fsH/1718363801538.jpg',
    text: "A patch of brambles in the meadow is a captivating sight, a stark contrast between the gentle openness of the meadow and the wild, untamed growth of the brambles. It's a scene that evokes a sense of nature's duality, where tranquility and wildness coexist, creating a dynamic and visually striking landscape.",
    date: '11-06-2024',
  },
  {
    id: 22,
    title: 'Horseshoe on the Pond',
    url: 'https://i.postimg.cc/X7F6STKb/1718363823744.jpg',
    text: '"Clear, still water reflects the world perfectly, just like a mindful mind can reflect reality without distortion"',
    signature: 'by Charlotte Joko Beck',
    date: '11-06-2024',
  },
  {
    id: 23,
    title: 'Bee Eating',
    url: 'https://i.postimg.cc/MpvZQsV3/1718363853702.jpg',
    text: 'The gabardera is one of the most common shrubs in Aragón. They can reach two or three meters in height, with branches often armed with aculeuses, sometimes curved spikes that form on the skin of the branch (different from the thorns, which are part of it; that is why it is possible to separate the aculeuses of the gabardera branch without damaging the bush). The leaves are compound, with odd leaflets (imparipinnate), with a serrated edge. The flowers have 5 sepals and 5 petals. The color of the petals varies depending on the species, white, pink or more or less intense red. They have numerous stamens. The fruit, the gabarda or tapaculos, is oval, glossy, reddish or orange, often with remains of the sepals at its apex. Inside are the seeds among numerous hairs.',
    date: '08-06-2024',
  },
  {
    id: 24,
    title: 'Happy Dog',
    url: 'https://i.postimg.cc/ZqXWRGQL/1718363915566.jpg',
    text: "A happy dog loves you unconditionally, no matter what kind of day you've had. They're always excited to see you, shower you with affection, and offer unwavering companionship.",
    date: '06-06-2024',
  },
  {
    id: 25,
    title: 'Red Geranio',
    url: 'https://i.postimg.cc/wTkRVbt6/1718363941697.jpg',
    text: '"Passion is like fire. It can burn brightly and illuminate our path, but it can also be destructive if not controlled."',
    signature: 'by Buddha',
    date: '05-06-2024',
  },
  {
    id: 26,
    title: 'Come With Me',
    url: 'https://i.postimg.cc/xTNFNMqy/1718363986560.jpg',
    text: 'Nature provides a sanctuary from the daily grind, promoting relaxation, stress relief, and a sense of peace. The vastness puts worries in perspective and reconnects you to something larger than yourself.',
    date: '04-06-2024',
  },
  {
    id: 27,
    title: 'Sun Coming Out',
    url: 'https://i.postimg.cc/NFH7F8bK/1718364279918.jpg',
    text: '"The mind is like the sky. The clouds may come and go, but the sky remains always."',
    signature: 'by Shantideva',
    date: '02-06-2024',
  },
  {
    id: 28,
    title: 'Clear Sky',
    url: 'https://i.postimg.cc/SQ2Ggqqm/1718364323427.jpg',
    text: '"If there is no vain cloud in your mind, for you it is a good season"',
    signature: 'by Charlotte Joko Beck',
    date: '02-06-2024',
  },
  {
    id: 29,
    title: 'Bright Hearts',
    url: 'https://i.postimg.cc/7Y10RZRr/1718364161226.jpg',
    text: '"Cultivate stillness within yourself and find the world in bloom."',
    signature: 'by Zen Master Dogen',
    date: '01-06-2024',
  },
  {
    id: 30,
    title: 'Wild Rose',
    url: 'https://i.postimg.cc/JnBB5rXg/1718364223529.jpg',
    text: '"Just as a seed becomes a beautiful flower, we too can transform and grow."',
    signature: 'by Buddha',
    date: '01-06-2024',
  },
  {
    id: 31,
    title: 'Painted Clouds',
    url: 'https://i.postimg.cc/cJ5yG3B0/1718716501208.jpg',
    text: '"The way is not in the sky. The way is in the heart."',
    signature: 'by Buddha',
    date: '30-05-2024',
  },
  {
    id: 32,
    title: 'Pine shade',
    url: 'https://i.postimg.cc/Y0Fw3Sgk/1718716644337.jpg',
    text: 'Amongst the pine needles and earthy scent, The dog revels in the moment, his energy spent. In the embrace of nature, he finds his joy, A loyal companion, his playful spirit does buoy.',
    date: '28-05-2024',
  },
  {
    id: 33,
    title: 'Beam of Light',
    url: 'https://i.postimg.cc/rm06VpfW/1718716602128.jpg',
    text: "In the quiet stillness of a forest glade, A beam of light breaks through the leafy shade. It pierces the darkness, a shaft of gold, Revealing the hidden wonders of the forest's soul.",
    date: '28-05-2024',
  },
  {
    id: 34,
    title: 'Dew on the Flowers',
    url: 'https://i.postimg.cc/8kY80LPH/1718716732275.jpg',
    text: "In the stillness of the morning, when the world is yet asleep, The dew on the flowers glistens, a delicate veil of sleep. It clings to the petals, a beading of moisture and grace, A gentle reminder of the mysteries of the night's embrace.",
    date: '28-05-2024',
  },
  {
    id: 35,
    title: 'Dog Nap',
    url: 'https://i.postimg.cc/wj0nDNPL/1718716955960.jpg',
    text: 'A good nap can be just what the body needs, a chance to rest and replenish. The soft embrace of a blanket, a haven of comfort and peace, can wash away the stresses of the day, leaving the mind at ease.',
    date: '25-05-2024',
  },
  {
    id: 36,
    title: 'Pink Sky',
    url: 'https://i.postimg.cc/ZR7kZdPJ/1718717213721.jpg',
    text: 'As shadows dance and merge, in the fading light, The world is bathed in pink, a magical sight. The day transforms to dusk, a peaceful reverie, In the arms of twilight, we find serenity.',
    date: '23-05-2024',
  },
  {
    id: 37,
    title: 'Flexible as Water',
    url: 'https://i.postimg.cc/ydtHcRDv/1718717384079.jpg',
    text: '"Nothing in the world is more flexible and yielding than water. Yet when it attacks the firm and the strong, none can withstand it, because they have no way to change it. So the flexible overcome the adamant, the yielding overcome the forceful. Everyone knows this, but no one can do it."',
    date: '18-05-2024',
  },
  {
    id: 38,
    title: 'Wet Dog',
    url: 'https://i.postimg.cc/C5z3KxJk/1718717436879.jpg',
    text: "It's fun being wet in this cool weather!",
    date: '18-05-2024',
  },
  {
    id: 39,
    title: 'Present Moment',
    url: 'https://i.postimg.cc/9XgVHv1y/1718717568552.jpg',
    text: 'Are you living the present moment? Look around and see.',
    date: '12-05-2024',
  },
  {
    id: 40,
    title: 'Big Oaks',
    url: 'https://i.postimg.cc/hjPFHrdC/1718717740310.jpg',
    text: "In the Aragon Pyrenees, where the wind whispers secrets to the trees, The Big Oak stands tall, a sentinel of the ancient woods. Its branches stretch towards the sky, a canopy of green and gold, A haven for creatures, a refuge from the world's cold.",
    date: '11-05-2024',
  },
  {
    id: 41,
    title: 'Happiness is the Path',
    url: 'https://i.postimg.cc/QCzrgTVf/1718717815420.jpg',
    text: '"There is no path to happiness. Happiness is the path."',
    signature: 'by Buddha',
    date: '07-05-2024',
  },
  {
    id: 42,
    title: 'Peace of Mind',
    url: 'https://i.postimg.cc/sDtrv7kX/1718718119401.jpg',
    text: '"No anger inside means no enemy outside."',
    signature: 'by Lama Zopa Rinpoche',
    date: '03-05-2024',
  },
  {
    id: 43,
    title: 'Amazed by Nature',
    url: 'https://i.postimg.cc/HxBmxKmD/1718718101882.jpg',
    text: 'Animals, like humans, have a deep appreciation for nature. They have evolved to live in harmony with their environment and have developed unique ways of interacting and adapting to their surroundings. We should do the same.',
    date: '03-05-2024',
  },
  {
    id: 44,
    title: 'Meditation Clouds',
    url: 'https://i.postimg.cc/sD3WbG6M/1718718196180.jpg',
    text: 'We are the mountain, the clouds our thoughts. Thoughts come, thoughts go. We remain. This is what we wish to observe in meditation. ',
    date: '03-05-2024',
  },
];
