import { Pic } from './pic.model';

export const picsData: Pic[] = [
  {
    id: 1,
    title: 'Geranios',
    url: 'https://i.postimg.cc/gkxSWZCh/1718362941135.jpg',
    text: '"Colorful geraniums that can be seen hanging on the walls of balconies are plants that captivate hearts with the tones that their petals preserve. The strong passionate red appears, the immaculate white in the corollas, they are flowers illuminated by streetlights, they reflect the illusion that is greening.',
    signature: 'by Fabio Robles',
    date: '12-06-2024',
  },
  {
    id: 2,
    title: 'Wild Flowers',
    url: 'https://i.postimg.cc/FRhC5nvF/1718362941118.jpg',
    text: 'The Aragon Pyrenees, a mountain range straddling the border between France and Spain, is a haven for wildflower enthusiasts.  From vibrant purple crocuses blanketing the slopes in spring to delicate alpine blooms carpeting the high meadows in summer, the region boasts a diverse and colorful tapestry of wildflowers.',
    date: '12-06-2024',
  },
  {
    id: 3,
    title: 'Piñas',
    url: 'https://i.postimg.cc/brBmnytd/1718362941154.jpg',
    text: 'The Aragon Pyrenees, with their vast stretches of pine forests, are home to several species of pine trees, each producing distinct pine cones.',
    date: '11-06-2024',
  },
  {
    id: 4,
    title: 'White Bells',
    url: 'https://i.postimg.cc/2y6H3b3P/1718362941166.jpg',
    text: 'Lily of the Valley (Convallaria majalis):  Delighting hikers with their sweet fragrance and delicate white bell-shaped flowers, lily of the valley thrives in the cool, moist forests of the Pyrenees.',
    date: '11-06-2024',
  },
  {
    id: 5,
    title: 'Pink Stars',
    url: 'https://i.postimg.cc/CMPPXNQY/1718362941182.jpg',
    text: '"He who has little is not poor, but he who desires much"',
    signature: 'by Seneca',
    date: '11-06-2024',
  },
  {
    id: 6,
    title: 'Purple Sticks',
    url: 'https://i.postimg.cc/KY2JBsR7/1718362941194.jpg',
    text: "The flowers of life's impermanence are not a cause for despair, but a reminder to cherish the present moment. Appreciate the beauty of the bloom in its entirety, from the vibrant hues of its petals to the delicate dewdrops clinging to its leaves.",
    date: '11-06-2024',
  },
  {
    id: 7,
    title: 'Purple Bell',
    url: 'https://i.postimg.cc/VL27LNwV/1718362941205.jpg',
    text: '"The bell of mindfulness is the voice of the Buddha within. Every sound can be a bell, calling us back to the present moment."',
    signature: 'by Thich Nhat Hanh',
    date: '11-06-2024',
  },
  {
    id: 8,
    title: 'Bright Sunset',
    url: 'https://i.postimg.cc/7L3tRrpQ/1718363021815.jpg',
    text: '"If you are attached to this life, you are not a Dharma practitioner. If you are attached to samsara, you have no renunciation. If you are attached to your own personal interest, you have no bodhicitta. If attachment arises, you do not have the vision."',
    signature: 'by Manjushri',
    date: '11-06-2024',
  },

  {
    id: 9,
    title: 'Cloud over the mountains',
    url: 'https://i.postimg.cc/C1KchfW8/1718363748142.jpg',
    text: '"Everything is subject to change. Nothing stays the same for long."',
    signature: 'by Buddha',
    date: '11-06-2024',
  },
  {
    id: 10,
    title: 'Cloudy Morning',
    url: 'https://i.postimg.cc/P5jst2K8/1718363764193.jpg',
    text: '"True peace comes from within you, it is not found anywhere else nor does it come from the hand of any person or thing. Peace is found in you."',
    signature: 'by Buddha',
    date: '11-06-2024',
  },
  {
    id: 11,
    title: 'Wild Meadow',
    url: 'https://i.postimg.cc/G2354fsH/1718363801538.jpg',
    text: "A patch of brambles in the meadow is a captivating sight, a stark contrast between the gentle openness of the meadow and the wild, untamed growth of the brambles. It's a scene that evokes a sense of nature's duality, where tranquility and wildness coexist, creating a dynamic and visually striking landscape.",
    date: '11-06-2024',
  },
  {
    id: 12,
    title: 'Horseshoe on the Watertight',
    url: 'https://i.postimg.cc/X7F6STKb/1718363823744.jpg',
    text: '"Clear, still water reflects the world perfectly, just like a mindful mind can reflect reality without distortion"',
    signature: 'by Charlotte Joko Beck',
    date: '11-06-2024',
  },
  {
    id: 13,
    title: 'Bee Eating',
    url: 'https://i.postimg.cc/MpvZQsV3/1718363853702.jpg',
    text: 'The gabardera is one of the most common shrubs in Aragón. They can reach two or three meters in height, with branches often armed with aculeuses, sometimes curved spikes that form on the skin of the branch (different from the thorns, which are part of it; that is why it is possible to separate the aculeuses of the gabardera branch without damaging the bush). The leaves are compound, with odd leaflets (imparipinnate), with a serrated edge. The flowers have 5 sepals and 5 petals. The color of the petals varies depending on the species, white, pink or more or less intense red. They have numerous stamens. The fruit, the gabarda or tapaculos, is oval, glossy, reddish or orange, often with remains of the sepals at its apex. Inside are the seeds among numerous hairs.',
    date: '08-06-2024',
  },
  {
    id: 14,
    title: 'Happy Dog',
    url: 'https://i.postimg.cc/ZqXWRGQL/1718363915566.jpg',
    text: "A happy dog loves you unconditionally, no matter what kind of day you've had. They're always excited to see you, shower you with affection, and offer unwavering companionship.",
    date: '06-06-2024',
  },
  {
    id: 15,
    title: 'Red Geranio',
    url: 'https://i.postimg.cc/wTkRVbt6/1718363941697.jpg',
    text: '"Passion is like fire. It can burn brightly and illuminate our path, but it can also be destructive if not controlled."',
    signature: 'by Buddha',
    date: '05-06-2024',
  },
  {
    id: 16,
    title: 'Come With Me',
    url: 'https://i.postimg.cc/xTNFNMqy/1718363986560.jpg',
    text: 'Nature provides a sanctuary from the daily grind, promoting relaxation, stress relief, and a sense of peace. The vastness puts worries in perspective and reconnects you to something larger than yourself.',
    date: '04-06-2024',
  },
  {
    id: 17,
    title: 'Sun Coming Out',
    url: 'https://i.postimg.cc/NFH7F8bK/1718364279918.jpg',
    text: '"The mind is like the sky. The clouds may come and go, but the sky remains always."',
    signature: 'by Shantideva',
    date: '02-06-2024',
  },
  {
    id: 18,
    title: 'Clear Sky',
    url: 'https://i.postimg.cc/SQ2Ggqqm/1718364323427.jpg',
    text: '"If there is no vain cloud in your mind, for you it is a good season"',
    signature: 'by Charlotte Joko Beck',
    date: '02-06-2024',
  },
  {
    id: 19,
    title: 'Bright Hearts',
    url: 'https://i.postimg.cc/7Y10RZRr/1718364161226.jpg',
    text: '"Cultivate stillness within yourself and find the world in bloom."',
    signature: 'by Zen Master Dogen',
    date: '01-06-2024',
  },
  {
    id: 20,
    title: 'Wild Rose',
    url: 'https://i.postimg.cc/JnBB5rXg/1718364223529.jpg',
    text: '"Just as a seed becomes a beautiful flower, we too can transform and grow."',
    signature: 'by Buddha',
    date: '01-06-2024',
  },
];
